version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my_postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: HandelsU
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"